# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qwr8gJGmtvTx2cZ73spYqgKPL4teXfgn
"""

import pandas as pd
import plotly.express as px
t_data = pd.read_csv('/content/drive/MyDrive/Tornados 2023-2.csv')
agg_data = t_data.groupby(['st', 'mag'])['loss'].sum().reset_index()
fig = px.bar(agg_data, x="st", y="loss", color="mag", title=" Total State Loss by Tornado Magnitude")
fig.show()

import plotly.express as px
import pandas as pd
t_data = pd.read_csv('/content/drive/MyDrive/Tornados 2023-2.csv')
loss_yearly = t_data.groupby(['yr'])['loss'].mean().reset_index()
fig = px.line(loss_yearly, x="yr", y="loss", title="Average Loss USD from tornados's Overtime")
fig.show()